services: 
  mongo: 
    environment: 
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    image: mongo
    ports: 
      - "27017:27017"
  mongo-express: 
    environment: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    image: mongo-express
    ports: 
      - "8080:8081"
version: "3"
